USE QLKS
go

--SELECT * FROM PHIEUDATPHONG;
--
--
--UPDATE PHIEUDATPHONG SET NGAYDI=GETDATE() WHERE MAKH='KH499070'
--GO

UPDATE HOADONPHONG
SET MANV = p.MANV,
    MAKH = p.MAKH,
    NGAY_LAP = p.NGAYLAP,
    THANHTIEN = p.THANHTIEN
FROM HOADONPHONG h
JOIN PHIEUDATPHONG p
ON h.MAPDK = p.MAPDK

UPDATE HOADONPHONG
SET PTTT = NULL
WHERE TINHTRANG = N'Chưa thanh toán'

-- select * from hoadonphong

---------1.TIM HOA DON PHONG------------------------------
DROP PROC IF EXISTS TimHoaDonPhong 
GO

CREATE PROCEDURE TimHoaDonPhong 
	@MAPDK varchar(15)
AS
	SELECT * FROM HOADONPHONG
	WHERE MAPDK = @MAPDK AND TINHTRANG != N'Đã thanh toán'
	ORDER BY NGAY_LAP DESC;

GO

--EXEC TimHoaDonPhong ''

--------2. DANH SACH HOA DON PHONG-----------------
DROP PROC IF EXISTS DSHDP 
GO

CREATE 
--ALTER 
PROCEDURE DSHDP 
AS
BEGIN
	SELECT * FROM HOADONPHONG WHERE TINHTRANG != N'Đã thanh toán'
	ORDER BY NGAY_LAP DESC;
END
GO


--EXEC DSHDP

--------3. CAP NHAT HOA DON------------------------
DROP PROC IF EXISTS CapNhatHoaDonPhong 
GO

CREATE
--ALTER
PROCEDURE CapNhatHoaDonPhong 
	@MAPDK VARCHAR(15),
    @PTTT NVARCHAR(30),
    @TINHTRANG NVARCHAR(50),
	@NOTE NVARCHAR(50), 
	@NGAYLAP DATETIME
AS
BEGIN
	DECLARE @MANV VARCHAR(8);
	SELECT TOP 1 @MANV = MANV FROM NHANVIEN WHERE BOPHAN = N'Lễ tân' ORDER BY NEWID();
	
	UPDATE HOADONPHONG 
	SET PTTT = @PTTT,
	TINHTRANG = @TINHTRANG,
	NOTE = @NOTE, 
	MANV = @MANV,
	NGAY_LAP = @NGAYLAP
	WHERE MAPDK = @MAPDK;

	UPDATE CHITIETDATPHONG
	SET NOTE = @NOTE
	WHERE MAPDK = @MAPDK;

	SELECT 'THE SELECTED RECEIVE HAS BEEN UPDATED' AS RESULT
END
GO

--------4. XOA HOA DON------------------------
DROP PROC IF EXISTS XoaHoaDonPhong 
GO

CREATE
--ALTER
PROCEDURE XoaHoaDonPhong 
	@MAPDK varchar(15)
AS
BEGIN
	DELETE FROM CHITIETDATPHONG WHERE MAPDK = @MAPDK;
	DELETE FROM HOADONPHONG WHERE MAPDK = @MAPDK;
	DELETE FROM PHIEUDATPHONG WHERE MAPDK = @MAPDK;

	SELECT 'THE SELECTED RECEIVE HAS BEEN DELETED' AS RESULT
END
GO

--------5. CHI TIET HOA DON------------------------
DROP PROC IF EXISTS ChiTietHoaDonPhong 
GO
CREATE PROCEDURE ChiTietHoaDonPhong 
	@MAPDK varchar(15)
AS
BEGIN
	SELECT  PDP.MAPDK, PDP.MANV, NV.HOTEN, PDP.NGAYLAP, TTD.MAKH, TTD.TENKH, TTD.CCCD, TTD.EMAIL, TTD.SDT, TTD.DIACHI, TTD.FAX, TTD.TENDOAN, TTD.SOLUONG, PDP.NGAYDEN, PDP.NGAYDI, PDP.SODEMLUUTRU, PDP.THANHTIEN,
			(SELECT STRING_AGG(CT.MAPHONG, ',') AS MAPHONGS
			 FROM CHITIETDATPHONG CT 
			 JOIN PHONG P ON CT.MAPHONG = P.MAPHONG
			 WHERE CT.MAPDK = @MAPDK
			 GROUP BY CT.MAPDK
			) AS DSPHONG,
			(SELECT COUNT(DISTINCT CT.MAPHONG) 
			 FROM CHITIETDATPHONG CT 
			 WHERE CT.MAPDK = @MAPDK
			) AS SOPHONG,
			(SELECT TOP (1) P.LOAIPHONG 
			 FROM CHITIETDATPHONG CT 
			 JOIN PHONG P ON CT.MAPHONG = P.MAPHONG
			 WHERE CT.MAPDK = @MAPDK
			 ) AS LOAIPHONG,
			 (SELECT TOP (1) CT.NOTE 
			 FROM CHITIETDATPHONG CT 
			 WHERE CT.MAPDK = @MAPDK
			 ) AS NOTE
	FROM PHIEUDATPHONG PDP 
	JOIN THONGTINDOAN TTD ON PDP.MAKH = TTD.MAKH	
	JOIN NHANVIEN NV ON NV.MANV = PDP.MANV
	WHERE MAPDK = @MAPDK;
END
GO

--exec ChiTietHoaDonPhong 'PDKc7fd4dd5a8f9';

