USE QLKS
go

--SELECT * FROM PHIEUDATPHONG;
--
--
--UPDATE PHIEUDATPHONG SET NGAYDI=GETDATE() WHERE MAKH='KH499070'
--GO

---------0. TimPhong------------------------------
DROP PROC IF EXISTS TimPhong 
GO

CREATE PROCEDURE TimPhong 
	@TuKhoa varchar(15)
AS
SELECT CTDP.MAPHONG,PDP.MAKH, TTD.TENKH, PDP.NGAYDEN,PDP.NGAYDI
FROM PHIEUDATPHONG PDP JOIN CHITIETDATPHONG CTDP ON PDP.MAPDK=CTDP.MAPDK
JOIN THONGTINDOAN TTD ON PDP.MAKH=TTD.MAKH
WHERE DATEPART(DAY, PDP.NGAYDI)=DATEPART(DAY,GETDATE()) AND PDP.MAKH=@TuKhoa OR CTDP.MAPHONG=@TuKhoa
GO

--EXEC TimPhong 'P201'
--GO

--------1.Xem danh sach phong tra------------------------------
DROP PROC IF EXISTS XemDSPTra 
GO

CREATE 
--alter
PROCEDURE XemDSPTra
AS
SELECT CTDP.MAPHONG,PDP.MAKH, TTD.TENKH, PDP.NGAYDEN,PDP.NGAYDI
FROM PHIEUDATPHONG PDP JOIN CHITIETDATPHONG CTDP ON PDP.MAPDK=CTDP.MAPDK
JOIN THONGTINDOAN TTD ON PDP.MAKH=TTD.MAKH
WHERE cast(PDP.NGAYDI AS DATE)=cast(GETDATE() AS DATE)

GO

--exec XemDSPTra

---------------------2. Danh Sach DVDK-----------------
DROP PROC IF EXISTS DSDVDK 
GO

CREATE 
--ALTER 
PROCEDURE DSDVDK 
	@MaKH varchar(15)
AS
SELECT PDP.MAPDK, DV.TENDV, PDKDV.SOLUONG, PDKDV.NGAYLAP
FROM PHIEUDATPHONG PDP JOIN PHIEU_DKDV_SP PDKDV ON PDP.MAPDK=PDKDV.MAPDK 
JOIN DICHVU DV ON PDKDV.MADV=DV.MADV
WHERE PDP.MAKH=@MaKH
go


--EXEC DSDVDK 'KH606532' 
select * from thongtindoan where makh = 'KH606532';
--SELECT * FROM PHIEUDATPHONG where makh = 'KH606532';
--SELECT * FROM PHIEU_DKDV_SP where makh = 'KH606532';


--------------------3. HOA DON------------------------
DROP PROC IF EXISTS HoaDon 
GO

CREATE
--ALTER
PROCEDURE HoaDon 
	@MaKH varchar(15)
AS
SELECT CTDP.MAPHONG, P.GIA, PDP.NGAYLAP
FROM HOADONPHONG HDP JOIN PHIEUDATPHONG PDP ON HDP.MAPDK=PDP.MAPDK 
JOIN CHITIETDATPHONG CTDP ON CTDP.MAPDK=PDP.MAPDK
JOIN PHONG P ON P.MAPHONG=CTDP.MAPHONG 
WHERE cast(PDP.NGAYDI AS DATE)=cast(GETDATE() AS DATE) AND PDP.MAKH=@MaKH

--SELECT  DV.TENDV,PDKDV.SOLUONG,PDKDV.NGAYLAP,PDKDV.NOTE FROM PHIEU_DKDV_SP PDKDV JOIN DICHVU DV ON DV.MADV=PDKDV.MADV
--WHERE PDKDV.MAKH=@MaKH


--select * from HOADONDV dv join HOADONPHONG p on dv.MAHD=p.MAHD
--select * from HOADONPHONG hdp join CHITIETDATPHONG ctdp on hdp.MAPDK=ctdp.MAPDK 
--order by hdp.MAPDK
--
--
--
----Lấy ra chi tiết đặt phòng và giá ti�?n mỗi phòng
--SELECT CTDP.MAPHONG, P.GIA, PDP.NGAYLAP
--FROM HOADONPHONG HDP JOIN PHIEUDATPHONG PDP ON HDP.MAPDK=PDP.MAPDK 
--JOIN CHITIETDATPHONG CTDP ON CTDP.MAPDK=PDP.MAPDK
--JOIN PHONG P ON P.MAPHONG=CTDP.MAPHONG 
--WHERE cast(PDP.NGAYDI AS DATE)=cast(GETDATE() AS DATE) AND PDP.MAKH='KH499070'
--
--
--
------Lấy ra tổng ti�?n 
----1. HOADON * PDP (MKH = @MKH và CHECKOUT = �?IỀU KIỆN HÔM NAY) 
----2. PDP * CTDP
----3. CTDP*P --> Tổng ti�?n cho các phòng
----4. Gán vào THANHTIEN (PDP) Gán vào HDP
--
--EXEC HoaDon 'KH606532' 